name: CI

on: 
  push:
    branches: [ Circular-list ]
  pull_request:
    branches: [ Circular-list ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential doxygen graphviz
        
    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        cmake -DBUILD_TESTS=ON ..
        make
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Generate docs
      run: |
        cd build
        make docs
