name: CI 

on:
  push:
    branches: [CI and testing]
  pull_request:
    branches: [CI and testing]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: "all checks were successful"
